name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: trace

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup development environment
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: cache rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}

      - name: lint
        run: lint:all
        shell: bash

      - name: Prepare driver and browsers
        run: cargo test hello

      - name: Test
        run: cargo test --all-targets -- --nocapture

      - name: coverage
        if: success() && matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/master'
        run: cargo tarpaulin --out Xml --verbose --exclude-files scripts/ tests/ src/build.rs src/main.rs src/generated.rs

      - name: Upload to codecov.io
        if: success() && matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/master'
        uses: codecov/codecov-action@v1.0.2
        with:
          file: cobertura.xml
